import * as React from 'react'
import { DataTable } from '@/components/shared/data-table'
import { PageSection } from '@/components/shared/page-section'
import {
  getAdminNotifications,
  markNotificationAsRead,
  processNotifications,
} from '@/features/notifications/api/notifications-api'
import { formatDateTime } from '@/lib/date'
import { ApiError } from '@/types/api'

function getNotificationBadge(type: string) {
  switch (type.toLowerCase()) {
    case 'lowstock':
      return 'br'
    case 'creditreminder':
      return 'ba'
    default:
      return 'bg'
  }
}

export function NotificationsPage() {
  const [result, setResult] = React.useState<
    Awaited<ReturnType<typeof getAdminNotifications>> | null
  >(null)
  const [isLoading, setIsLoading] = React.useState(true)
  const [isProcessing, setIsProcessing] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)

  const loadNotifications = React.useCallback(async () => {
    try {
      setError(null)
      const nextResult = await getAdminNotifications(1, 20)
      setResult(nextResult)
    } catch (loadError) {
      setError(
        loadError instanceof ApiError || loadError instanceof Error
          ? loadError.message
          : 'Unable to load notifications.',
      )
    } finally {
      setIsLoading(false)
    }
  }, [])

  React.useEffect(() => {
    queueMicrotask(() => {
      void loadNotifications()
    })
  }, [loadNotifications])

  async function handleProcessAlerts() {
    setIsProcessing(true)
    setError(null)

    try {
      await processNotifications()
      await loadNotifications()
    } catch (processError) {
      setError(
        processError instanceof ApiError || processError instanceof Error
          ? processError.message
          : 'Unable to process alerts.',
      )
    } finally {
      setIsProcessing(false)
    }
  }

  async function handleMarkAsRead(notificationId: number) {
    try {
      await markNotificationAsRead(notificationId)
      setResult((current) =>
        current
          ? {
              ...current,
              items: current.items.map((item) =>
                item.notificationId === notificationId
                  ? {
                      ...item,
                      isRead: true,
                      readAt: new Date().toISOString(),
                    }
                  : item,
              ),
            }
          : current,
      )
    } catch (markError) {
      setError(
        markError instanceof ApiError || markError instanceof Error
          ? markError.message
          : 'Unable to mark notification as read.',
      )
    }
  }

  return (
    <PageSection
      actions={
        <button
          className="tb-btn primary"
          disabled={isProcessing}
          onClick={() => void handleProcessAlerts()}
          type="button"
        >
          {isProcessing ? 'Processing...' : 'Process alerts'}
        </button>
      }
      description="Low-stock and overdue-credit notifications are generated by the backend alert processor and surfaced here for admin review."
      title="Notifications"
    >
      {error ? (
        <div className="mb-4 rounded-2xl border border-[var(--vs-red)]/15 bg-[var(--vs-red-100)] px-4 py-3 text-sm text-[var(--vs-red)]">
          {error}
        </div>
      ) : null}

      <DataTable
        columns={[
          {
            key: 'title',
            header: 'Notification',
            render: (item) => (
              <div>
                <div className="pn">{item.title}</div>
                <div className="pc">{item.message}</div>
              </div>
            ),
          },
          {
            key: 'notificationType',
            header: 'Type',
            render: (item) => (
              <span className={`badge ${getNotificationBadge(item.notificationType)}`}>
                {item.notificationType}
              </span>
            ),
          },
          {
            key: 'createdAt',
            header: 'Created',
            render: (item) => formatDateTime(item.createdAt),
          },
          {
            key: 'status',
            header: 'Status',
            render: (item) =>
              item.isRead ? (
                <span className="badge bg">Read</span>
              ) : (
                <span className="badge ba">Unread</span>
              ),
          },
          {
            key: 'action',
            header: 'Action',
            render: (item) =>
              item.isRead ? (
                <span className="pc">Completed</span>
              ) : (
                <button
                  className="tb-btn"
                  onClick={() => void handleMarkAsRead(item.notificationId)}
                  type="button"
                >
                  Mark read
                </button>
              ),
          },
        ]}
        emptyMessage={
          isLoading ? 'Loading notifications...' : 'No notifications available.'
        }
        rows={result?.items ?? []}
      />
    </PageSection>
  )
}
